// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yoajnmmjhmakadjnhmry.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlvYWpubW1qaG1ha2Fkam5obXJ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyNDE5MDYsImV4cCI6MjA2NDgxNzkwNn0.bKf07hi5HDO0syoW28VpuTXMMNQuuYQxERL4CGhsLVU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);